version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=git_tui
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/app
      - /app/__pycache__
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: git_tui
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: